name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mydb
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: mydb
      DB_USER: root
      DB_PASSWORD: ""
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DEBUG: 'True'
      SECRET_KEY: dummysecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Black (check only)
        run: black --check .
        
      - name: Wait for MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL..."; sleep 2;
          done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
