name: Django CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: Alina123@
          MYSQL_DATABASE: Django-rest-api
          MYSQL_USER: root
          MYSQL_PASSWORD: Alina123@
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: mysql://root:Alina123@localhost:3306/Django-rest-api
      DEBUG: 'True'
      SECRET_KEY: dummysecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mysqlclient

      - name: Wait for MySQL
        run: |
          for i in {30..0}; do
            mysqladmin ping -h localhost -uroot -pAlina123@ && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
